// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tHfoxu6XFvmk837xn6JEtW
// Component: JlH9ogfVmy
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_vercel_analytics.module.css"; // plasmic-import: tHfoxu6XFvmk837xn6JEtW/projectcss
import sty from "./PlasmicStatus.module.css"; // plasmic-import: JlH9ogfVmy/css

export type PlasmicStatus__VariantMembers = {};
export type PlasmicStatus__VariantsArgs = {};
type VariantPropType = keyof PlasmicStatus__VariantsArgs;
export const PlasmicStatus__VariantProps = new Array<VariantPropType>();

export type PlasmicStatus__ArgsType = {};
type ArgPropType = keyof PlasmicStatus__ArgsType;
export const PlasmicStatus__ArgProps = new Array<ArgPropType>();

export type PlasmicStatus__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultStatusProps {
  className?: string;
}

function PlasmicStatus__RenderFunc(props: {
  variants: PlasmicStatus__VariantsArgs;
  args: PlasmicStatus__ArgsType;
  overrides: PlasmicStatus__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__qpSxw
        )}
      >
        {"Status: "}
      </div>

      <div className={classNames(defaultcss.all, sty.box__qg1Ch)} />

      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__vnlog
        )}
      >
        {" All systems normal."}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStatus__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStatus__VariantsArgs;
    args?: PlasmicStatus__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStatus__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStatus__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStatus__ArgProps,
      internalVariantPropNames: PlasmicStatus__VariantProps
    });

    return PlasmicStatus__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStatus";
  } else {
    func.displayName = `PlasmicStatus.${nodeName}`;
  }
  return func;
}

export const PlasmicStatus = Object.assign(
  // Top-level PlasmicStatus renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStatus
    internalVariantProps: PlasmicStatus__VariantProps,
    internalArgProps: PlasmicStatus__ArgProps
  }
);

export default PlasmicStatus;
/* prettier-ignore-end */
