// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tHfoxu6XFvmk837xn6JEtW
// Component: CFp7a5ZuqR
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeaderLink from "../../HeaderLink"; // plasmic-import: TzGc970Ffx/component
import AnalyticsPageContent from "../../AnalyticsPageContent"; // plasmic-import: VR1e9QZukPo/component
import FooterLink from "../../FooterLink"; // plasmic-import: 8UTBVvBWCN/component
import Social from "../../Social"; // plasmic-import: UEtI0aDH9l/component
import Status from "../../Status"; // plasmic-import: JlH9ogfVmy/component
import FooterExpando from "../../FooterExpando"; // plasmic-import: vcKKQo6nI4/component
import Separator from "../../Separator"; // plasmic-import: R1EHrPSYL9/component

import { ScreenContext, ScreenValue } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: cYH_9Q0rIf-f/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_vercel_analytics.module.css"; // plasmic-import: tHfoxu6XFvmk837xn6JEtW/projectcss
import sty from "./PlasmicVercelPageShell.module.css"; // plasmic-import: CFp7a5ZuqR/css

import VercelLogoIcon from "./icons/PlasmicIcon__VercelLogo"; // plasmic-import: zpcflSlTXc/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: QRRND2nGCn/icon

export type PlasmicVercelPageShell__VariantMembers = {};
export type PlasmicVercelPageShell__VariantsArgs = {};
type VariantPropType = keyof PlasmicVercelPageShell__VariantsArgs;
export const PlasmicVercelPageShell__VariantProps = new Array<VariantPropType>();

export type PlasmicVercelPageShell__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicVercelPageShell__ArgsType;
export const PlasmicVercelPageShell__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicVercelPageShell__OverridesType = {
  root?: p.Flex<"div">;
  news?: p.Flex<"div">;
  header?: p.Flex<"div">;
  analyticsPageContent?: p.Flex<typeof AnalyticsPageContent>;
  footer?: p.Flex<"div">;
};

export interface DefaultVercelPageShellProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicVercelPageShell__RenderFunc(props: {
  variants: PlasmicVercelPageShell__VariantsArgs;
  args: PlasmicVercelPageShell__ArgsType;
  overrides: PlasmicVercelPageShell__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: React.useContext(ScreenContext)
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {false ? (
        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img__f6IUv)}
          role={"img"}
          src={"/plasmic/vercel_analytics/images/vercelcomAnalyticsLaptopWithMdpiScreenpng.png"}
        />
      ) : null}
      {false ? (
        <img
          alt={""}
          className={classNames(defaultcss.img, sty.img__zp9Lw)}
          role={"img"}
          src={"/plasmic/vercel_analytics/images/vercelcomAnalyticsMotoG4Png.jpeg"}
        />
      ) : null}

      <div className={classNames(defaultcss.all, sty.box__wG84A)}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"news"}
          data-plasmic-override={overrides.news}
          hasGap={true}
          className={classNames(defaultcss.all, sty.news)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__yUfxX
            )}
          >
            {"$40M to Build the Next Web"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__t0SW
            )}
          >
            {"Read ->"}
          </div>
        </p.Stack>

        <div
          data-plasmic-name={"header"}
          data-plasmic-override={overrides.header}
          className={classNames(defaultcss.all, sty.header)}
        >
          <VercelLogoIcon
            className={classNames(defaultcss.all, sty.svg__e2Nao)}
            role={"img"}
          />

          {(hasVariant(globalVariants, "screen", "tablet") ? true : false) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box___7UOy8)}
            >
              <HeaderLink
                className={classNames("__wab_instance", sty.headerLink___1TpKf)}
              />

              <HeaderLink
                className={classNames("__wab_instance", sty.headerLink__bbAoA)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__xuvTn
                  )}
                >
                  {"Analytics"}
                </div>
              </HeaderLink>

              <HeaderLink
                className={classNames("__wab_instance", sty.headerLink__afJla)}
              >
                {"Pricing"}
              </HeaderLink>
            </p.Stack>
          ) : null}
          {(hasVariant(globalVariants, "screen", "tablet") ? true : false) ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__a0Xc9)}
            >
              <HeaderLink
                className={classNames("__wab_instance", sty.headerLink___6EyG2)}
              >
                {"Contact"}
              </HeaderLink>

              <HeaderLink
                className={classNames("__wab_instance", sty.headerLink__vxrrT)}
              >
                {"Login"}
              </HeaderLink>

              <HeaderLink
                className={classNames("__wab_instance", sty.headerLink__l5FeH)}
              >
                <div className={classNames(defaultcss.all, sty.box__pPYsg)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ujAfw
                    )}
                  >
                    {"Sign up"}
                  </div>
                </div>
              </HeaderLink>
            </p.Stack>
          ) : null}
          {(hasVariant(globalVariants, "screen", "tablet") ? false : true) ? (
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__jc4Cx)}
              role={"img"}
              src={"/plasmic/vercel_analytics/images/menu.png"}
            />
          ) : null}
        </div>

        <p.PlasmicSlot
          defaultContents={
            <AnalyticsPageContent
              data-plasmic-name={"analyticsPageContent"}
              data-plasmic-override={overrides.analyticsPageContent}
              className={classNames("__wab_instance", sty.analyticsPageContent)}
            />
          }
          value={args.children}
        />

        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            hasGap={true}
            className={classNames(defaultcss.all, sty.footer)}
          >
            {(hasVariant(globalVariants, "screen", "tablet") ? true : false) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__o4WV)}
              >
                <div className={classNames(defaultcss.all, sty.box__eTyai)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__wrjrl)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___170Nb
                      )}
                    >
                      {"Frameworks"}
                    </div>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__o6OqB
                      )}
                    >
                      {"Next.js"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__qx8P4
                      )}
                    >
                      {"Create React App"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__th6U
                      )}
                    >
                      {"Gatsby"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__zP2Yw
                      )}
                    >
                      {"Nuxt.js"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__cQs3
                      )}
                    >
                      {"Vue"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink___0W3RT
                      )}
                    >
                      {"Angular"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__ad81M
                      )}
                    >
                      {"More Frameworks"}
                    </FooterLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box___5YFrq)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__jCeM9
                      )}
                    >
                      {"Resources"}
                    </div>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__ytztO
                      )}
                    >
                      {"Documentation"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__guqf1
                      )}
                    >
                      {"Guides"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__ru46C
                      )}
                    >
                      {"Knowledge"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__xq4D
                      )}
                    >
                      {"API Reference"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink___5Ql7E
                      )}
                    >
                      {"Blog"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__o2JJh
                      )}
                    >
                      {"Changelog"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__aywpO
                      )}
                    >
                      {"OSS"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink___2M9I
                      )}
                    >
                      {"Command-Line"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__xynf
                      )}
                    >
                      {"Integrations"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__zpWz8
                      )}
                    >
                      {"Partners"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink___0Xq0Y
                      )}
                    >
                      {"Support"}
                    </FooterLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__x79Z)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__gj6Ij
                      )}
                    >
                      {"Company"}
                    </div>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__j7PxY
                      )}
                    >
                      {"Home"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__t5Y23
                      )}
                    >
                      {"About"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__nWm9
                      )}
                    >
                      {"Careers"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__v5Ms
                      )}
                    >
                      {"Pricing"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__oy73P
                      )}
                    >
                      {"Security"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink___5HKaL
                      )}
                    >
                      {"Next.js Conf"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__brybD
                      )}
                    >
                      {"Contact Us"}
                    </FooterLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__lr82D)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___3XVL
                      )}
                    >
                      {"Legal"}
                    </div>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__w9BYp
                      )}
                    >
                      {"Privacy Policy"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__gGfkW
                      )}
                    >
                      {"Terms of Service"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__mrVVa
                      )}
                    >
                      {"Trademark Policy"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__iu7JH
                      )}
                    >
                      {"Inactivity Policy"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__kszMk
                      )}
                    >
                      {"DPA"}
                    </FooterLink>

                    <FooterLink
                      className={classNames(
                        "__wab_instance",
                        sty.footerLink__dyvec
                      )}
                    >
                      {"SLA"}
                    </FooterLink>
                  </p.Stack>
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__zS39K)}
                >
                  <VercelLogoIcon
                    className={classNames(defaultcss.all, sty.svg__mHxSe)}
                    role={"img"}
                  />

                  <div className={classNames(defaultcss.all, sty.box___1Dyqz)}>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__jd7Rs
                      )}
                    >
                      {"Copyright © 2021 Vercel Inc. All rights reserved."}
                    </div>

                    <Social
                      className={classNames(
                        "__wab_instance",
                        sty.social__uLbcj
                      )}
                    />

                    <Status
                      className={classNames(
                        "__wab_instance",
                        sty.status__ulQ1P
                      )}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__tn1Jq)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___2IBv
                        )}
                      >
                        {"Light"}
                      </div>

                      <IconIcon
                        className={classNames(defaultcss.all, sty.svg__umO1)}
                        role={"img"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </p.Stack>
            ) : null}
            {(hasVariant(globalVariants, "screen", "tablet") ? false : true) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__rA57V)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__ica2T)}
                >
                  <FooterExpando
                    className={classNames(
                      "__wab_instance",
                      sty.footerExpando___1KXql
                    )}
                  >
                    {"Frameworks"}
                  </FooterExpando>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator___2TbHy
                    )}
                  />

                  <FooterExpando
                    className={classNames(
                      "__wab_instance",
                      sty.footerExpando___8Zm9N
                    )}
                  >
                    {"Resources"}
                  </FooterExpando>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__nCrSq
                    )}
                  />

                  <FooterExpando
                    className={classNames(
                      "__wab_instance",
                      sty.footerExpando__vPewe
                    )}
                  >
                    {"Company"}
                  </FooterExpando>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__wF4HW
                    )}
                  />

                  <FooterExpando
                    className={classNames(
                      "__wab_instance",
                      sty.footerExpando__zr6FZ
                    )}
                  >
                    {"Legal"}
                  </FooterExpando>
                </p.Stack>

                <VercelLogoIcon
                  className={classNames(defaultcss.all, sty.svg__vzema)}
                  role={"img"}
                />

                <Status
                  className={classNames("__wab_instance", sty.status__oKtev)}
                />

                <Social
                  className={classNames("__wab_instance", sty.social___4809R)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__mps9N
                  )}
                >
                  {"Copyright © 2021 Vercel Inc. All rights reserved."}
                </div>
              </p.Stack>
            ) : null}
          </p.Stack>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "news", "header", "analyticsPageContent", "footer"],
  news: ["news"],
  header: ["header"],
  analyticsPageContent: ["analyticsPageContent"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  news: "div";
  header: "div";
  analyticsPageContent: typeof AnalyticsPageContent;
  footer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVercelPageShell__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVercelPageShell__VariantsArgs;
    args?: PlasmicVercelPageShell__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVercelPageShell__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicVercelPageShell__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicVercelPageShell__ArgProps,
      internalVariantPropNames: PlasmicVercelPageShell__VariantProps
    });

    return PlasmicVercelPageShell__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVercelPageShell";
  } else {
    func.displayName = `PlasmicVercelPageShell.${nodeName}`;
  }
  return func;
}

export const PlasmicVercelPageShell = Object.assign(
  // Top-level PlasmicVercelPageShell renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    news: makeNodeComponent("news"),
    header: makeNodeComponent("header"),
    analyticsPageContent: makeNodeComponent("analyticsPageContent"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicVercelPageShell
    internalVariantProps: PlasmicVercelPageShell__VariantProps,
    internalArgProps: PlasmicVercelPageShell__ArgProps
  }
);

export default PlasmicVercelPageShell;
/* prettier-ignore-end */
